#!/usr/bin/env bash
# installs nginx and configure
# Then prints hello world

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

sudo sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.github.com\/fauroti;\n\t}\n/g" /etc/nginx/sites-avaialable/default

sudo service nginx start
