#!/usr/bin/env bash
# installs nginx and configure
# Then prints hello world

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me www.github.com/faturoti permanent;' /etc/nginx/sites-avaialable/default

sudo service nginx start
