#!/usr/bin/env bash
# installs nginx and configure
# Then prints hello world

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
ech0 "Ceci n'est pas une page" > /var/www/html/404.html

sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.github.com\/faturoti;\n\t}\n/g" /etc/nginx/sites-available/default
sed -i "s/server_name _;/server_name _;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}\n/g" /etc/nginx/sites-avaialable/default

sudo service nginx start
