#!/usr/bin/env bash
# to set up server
# install and update engine
sudo apt-get update -y
sudo apt-get install -y

# set the index and 404 files to load
echo "Hello World!" > index.html
sudo mv index.html /var/www/html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Set up server config file
printf %s "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   add_header X-Served-By $HOSTNAME;
   
   root /var/www/html;
   index index.html index.htm index.nginx-debian.html;

   location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }

   error_page 404 /404.html;
   location /404 {
	internal;
   }
}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
