#!/usr/bin/env bash
# To to change user on which nginx is running

sed -i "s/#user www-data/user" nginx/ /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
